inputs:
  semver:
    required: true
    type: string
  tag:
    required: true
    type: string

runs:
  using: composite
  steps:
  - name: Zip submitter plugin
    shell: bash
    run: |
      mkdir dist_extras
      cd src/deadline/keyshot_submitter
      zip -r  ../../../dist_extras/keyshot_submitter_plugin_${{inputs.semver}}.zip .
      cd ../../../
