inputs:
  semver:
    required: true
    type: string

runs:
  using: composite
  steps:
  - name: Update plugin Version
    shell: bash
    run: |
      sed -i "s/^# VERSION.*/# VERSION ${{inputs.semver}}/" ./src/submitter.py
      git add ./src/submitter.py 