set DEADLINE_CLOUD_PYTHONPATH="%CONDA_PREFIX%/Lib"
set DEADLINE_KEYSHOT_EXE="%CONDA_PREFIX%/Scripts/keyshot_headless.bat"
set KEYSHOT_EXECUTABLE="%CONDA_PREFIX%/Scripts/keyshot_headless.bat"
set PYTHONPATH=%CONDA_PREFIX%;%CONDA_PREFIX%/Lib;%CONDA_PREFIX%/Lib/bin;%CONDA_PREFIX%/Lib/site-packages;%PYTHONPATH%
