MSYS_NO_PATHCONV=1 export DEADLINE_CLOUD_PYTHONPATH="$CONDA_PREFIX/Lib"
MSYS_NO_PATHCONV=1 export DEADLINE_KEYSHOT_EXE="$CONDA_PREFIX/Scripts/keyshot_headless.bat"
MSYS_NO_PATHCONV=1 export KEYSHOT_EXECUTABLE="$CONDA_PREFIX/Scripts/keyshot_headless.bat"
MSYS_NO_PATHCONV=1 export PYTHONPATH="$CONDA_PREFIX;$CONDA_PREFIX/Lib;$CONDA_PREFIX/Lib/bin;$CONDA_PREFIX/Lib/site-packages;${PYTHONPATH:-}"
